### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by davidbrochart** [developmentseed/object-store-rs#34]
I find `object-store-rs` a bit ambiguous, as it might suggest this is a Rust package. Maybe `object-store-py` would be better?

**Comment by kylebarron** [comment]
There are already [`object-store`](https://pypi.org/project/object-store/) and [`object-store-python`](https://pypi.org/project/object-store-python/) projects on PyPI. I'm not great at naming but I figured that if you're `pip install`'ing a package, even if it has a `_rs` suffix, you know it's still a Python package

**Comment by davidbrochart** [comment]
Sure but then if there is a conda package it will be confusing.

**Comment by kylebarron** [comment]
I'm not sure if `object-store-py` is even distinct enough from `object-store-python` to publish it to pypi
